### ISSUE TITLE
Error trying to use `predict.py` script

### ISSUE THREAD

**Issue by paucarrecardona** [NVIDIA-AI-IOT/sdg_pallet_model#9]
Using `predict.py` I'm getting errors both using `v0.4.0` and `v.0.5.0` of `torch2trt`

- Using `v0.5.0` `torch2trt` I'm getting:
```
Traceback (most recent call last):
  File "/home/pau/sdg_pallet_model/predict.py", line 112, in <module>
    heatmap, vectormap = model(x)
  File "/home/pau/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pau/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch2trt-0.5.0-py3.10.egg/torch2trt/trt_module.py", line 169, in forward
    return self._forward_post_10(*inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch2trt-0.5.0-py3.10.egg/torch2trt/trt_module.py", line 141, in _forward_post_10
    self.context.set_tensor_address(input_name, data_ptr)
  File "/home/pau/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TRTModule' object has no attribute 'context'
```

- Using `v0.4.0` `torch2trt` I'm getting:
```
$ python3 predict.py pallet.engine images/test_image_1.jpg --output=image.jpg
/home/pau/.local/lib/python3.10/site-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[08/07/2024-14:45:51] [TRT] [E] IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 239, Serialized Engine Version: 236)
Traceback (most recent call last):
  File "/home/pau/sdg_pallet_model/predict.py", line 112, in <module>
    heatmap, vectormap = model(x)
  File "/home/pau/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pau/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch2trt-0.4.0-py3.10.egg/torch2trt/torch2trt.py", line 548, in forward
    idx = self.engine.get_binding_index(input_name)
AttributeError: 'NoneType' object has no attribute 'get_binding_index'
```

**Comment by paucarrecardona** [comment]
Solved it:
- `torch2trt` needs to be `v0.4.0` branch
- Python tensorrt should be `8.6.1`: `pip install tensorrt==8.6.1`
- TensorRT in system should be `8.6.1`: `apt list --installed | grep libnvinfer` should point to `8.6.1`

**Comment by stefangthb** [comment]
Hi @paucarrecardona, I see that you could download the onnx model. Could you please by any chance share it with me as I can't get access to it. Thank you!
